# Generated by Django 2.2.4 on 2020-01-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('website', models.CharField(max_length=128)),
                ('job_tags', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('bio', models.TextField(max_length=64)),
                ('linkedin_link', models.CharField(max_length=128)),
                ('github_link', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Busy', 'Busy')], default='Open', max_length=64)),
                ('job_tags', models.TextField(blank=True)),
                ('skills', models.TextField(blank=True)),
                ('previous_contracts', models.TextField(blank=True)),
            ],
        ),
    ]
