# Generated by Django 2.2.4 on 2020-01-12 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200111_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='company_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='client',
            name='website',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='github_link',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='linkedin_link',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
