# Generated by Django 2.2.4 on 2020-01-12 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_client_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultant',
            name='job_tags',
        ),
    ]
