# Generated by Django 2.2.4 on 2020-01-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultant',
            name='skills',
        ),
        migrations.AddField(
            model_name='consultant',
            name='skills',
            field=models.ManyToManyField(blank=True, to='profiles.Skill'),
        ),
    ]
