# Generated by Django 2.2.4 on 2020-01-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('summary', models.TextField(blank=True)),
                ('salary', models.CharField(blank=True, max_length=128)),
                ('skills', models.TextField(blank=True)),
                ('jobTags', models.TextField(blank=True)),
                ('client', models.CharField(max_length=128)),
                ('applicants', models.TextField(blank=True)),
                ('team', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Closed', 'Closed')], max_length=64)),
            ],
        ),
    ]
