# Generated by Django 2.2.4 on 2020-01-11 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contracts',
            new_name='Contract',
        ),
    ]
