# Generated by Django 3.0.2 on 2020-01-12 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_client_bio'),
        ('contracts', '0002_auto_20200111_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='applicants',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='team',
        ),
        migrations.AlterField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Client'),
        ),
    ]
